### Get all topics (To Be Implemented)
GET http://localhost:8080/topics
Accept: application/hal+json

### Get specific topic (To Be Implemented)
GET http://localhost:8080/topics/topic1
Accept: application/hal+json

### Get Atom feed (To Be Implemented)
GET http://localhost:8080/feed/atom
Accept: application/atom+xml

### Get RSS feed (To Be Implemented)
GET http://localhost:8080/feed/rss
Accept: application/rss+xml

### Examples with Basic Authentication (when enabled)

### Get topics with auth (To Be Implemented)
GET http://localhost:8080/topics
Accept: application/hal+json
Authorization: Basic user password

### Get specific topic with auth (To Be Implemented)
GET http://localhost:8080/topics/topic1
Accept: application/hal+json
Authorization: Basic admin admin
